Set up a "Hello world" project with two apps 🥇
ismailmunyentwari9/hello-rails-back-end pull request #1
Opened 2023-07-11 21:40 UTC by ismailmunyentwari9

# What I have done in this project 🥇 

- [ ] Create a new Rails API app called 'hello-rails-back-end'.
- [ ] Initialize  project with Git.
- [ ] Make sure that  project has a Postgres database set up.
- [ ] Create a table for storing  messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting
# 🧠  skills gained 🖲️ 

- [ ] Implement a connection between a Ruby on Rails back-end and React front-end.
- [ ] Understand pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

2023-07-11 21:48 UTC, DammyShittu reviewed
Hi @ismailmunyentwari9,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You should have an open pull request in the frontend repo containing the changes. Kindly add that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-11 22:00 UTC, DammyShittu reviewed
Hi @ismailmunyentwari9,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Your frontend repo does not have a descriptive readme documentation

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-12 08:34 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @ismailmunyentwari9 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Use GitHub Flow
- ✔️ Create an API endpoint

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 08:34 UTC, abdulhamiid commented on README.md
> +</details>
I notice that all the links in the `Tech Stack` is broken, kindly fix this please, let's avoid broken links in our README for a professional repository 🤗

2023-07-12 08:34 UTC, abdulhamiid commented on app/controllers/api/greetings_controller.rb
> +end
![image](https://github.com/ismailmunyentwari9/hello-rails-back-end/assets/78251927/897ad760-b4a7-4a16-8229-d7c4f412d9b7)

Your API endpoint selects a random greeting from your table 💯 👍

2023-07-14 12:51 UTC, afanimartin approved these changes
Hi @ismailmunyentwari9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Broken links fixed

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 06:24 UTC, merged